ALTER TABLE "Farm" ADD COLUMN IF NOT EXISTS "bankName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Farm" ADD COLUMN IF NOT EXISTS "bankAccount" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Farm" ADD COLUMN IF NOT EXISTS "bankAccountName" TEXT NOT NULL DEFAULT '';
